name: genai_agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # Core Dependencies
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
    - pydantic>=2.4.2
    - python-dotenv>=1.0.0

    
    # Agent and LLM Dependencies
    - langchain>=0.1.0
    - langgraph>=0.1.0
    - langchain-community>=0.1.0
    - openai>=1.3.0
    - pinecone-client>=2.2.4

    
    # Data Processing
    - python-dateutil>=2.8.2
    - pytz>=2023.3
    
    # Testing
    - pytest>=7.4.3
    - pytest-asyncio>=0.21.1
    - pytest-cov>=4.1.0
    
    # Development Tools
    - black>=23.11.0
    - isort>=5.12.0
    - flake8>=6.1.0
    - mypy>=1.7.0
    
    # Monitoring and Logging
    - prometheus-client>=0.19.0
    - elasticsearch>=8.11.0
    - python-json-logger>=2.0.7 